# Change these first
owner: didx-xyz # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

assignees:
  - rblaine95
  - wdbasson

sites:
  - name: SSI Trust Registry
    url: https://trust-registry.didx.co.za/api/registry

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: upptime.didx.co.za
  baseUrl: /
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: |-
    This is a status page of various endpoints hosted by DIDx.

    This page is generated and maintained with **real-time** data from our [GitHub repository](https://github.com/didx-xyz/upptime).

    No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: DIDx
      href: https://www.didx.co.za
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  theme: dark

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
