owner: didx-xyz
repo: upptime

assignees:
  - rblaine95
  - wdbasson

sites:
  - name: SSI Trust Registry
    url: https://trust-registry.didx.co.za/api/registry
    icon: https://www.didx.co.za/assets/images/logo/favourite_icon.png

status-website:
  cname: upptime.didx.co.za
  baseUrl: /
  logoUrl: https://avatars.githubusercontent.com/u/51539199
  name: did:up
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: |-
    This is a status page of various endpoints hosted by DIDx.

    This page is generated and maintained with **real-time** data from our [GitHub repository](https://github.com/didx-xyz/upptime).

    No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime).

    _This page is automatically updated on a best-effort basis every 5-30 minutes_
  navbar:
    - title: Home
      href: https://www.didx.co.za
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  theme: ocean

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
